{"uuid": "fe71a3c4-5d73-40c5-919b-3ab3c56ee44a", "children": ["20c65088-f8f8-4a46-9e38-6d39d4bc830a"], "befores": [{"name": "cau_hinh", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: Could not reach host. Are you offline?\n", "trace": "  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"e:\\Doan4\\codedoan4\\tests\\conftest.py\", line 37, in cau_hinh\n    service = Service(ChromeDriverManager().install())\n                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\chrome.py\", line 40, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 35, in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 110, in find_driver\n    key = self.__get_metadata_key(driver)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 144, in __get_metadata_key\n    driver_version = self.get_cache_key_driver_version(driver)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 154, in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver.py\", line 48, in get_driver_version_to_download\n    return self.get_latest_release_version()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\drivers\\chrome.py\", line 59, in get_latest_release_version\n    response = self._http_client.get(url)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py\", line 35, in get\n    raise exceptions.ConnectionError(f\"Could not reach host. Are you offline?\")\n"}, "start": 1760576156808, "stop": 1760576173987}], "start": 1760576156808, "stop": 1760576174268}